base_path: "D:/Photogrammetry"
dev_base_path: "/Users/ananth/Desktop/tarp-field-test"
stage_folders:
  raw_images:   "2026/Raw Images"
  aligned:      "2026/Aligned"
  moved_to_msi: "C:/Users/Photogrammetry/SynologyDrive/To Be Processed"
gsheets_spreadsheet_id: "1r6TMtVEl6wIAAO8FNEXW1qkkFeAxumyyRsFSE4vHIwI"
host: 127.0.0.1
port: 8001